"""Does this set of reservations physically fit in this space, all year?

This is the part of a peer-to-peer storage marketplace that a scalar
"remaining square feet" counter cannot answer. A 20 x 30 garage with 400 sq ft
already committed has 200 sq ft left on paper, and still may not have room for
a 10 x 20 boat, because the leftover space is two separate 10 x 10 pockets, or
because parking the boat there would wall in a renter who needs to get a
motorcycle out in March.

Model
-----
* The space is a W x D rectangle with the access edge at y = 0.
* Each reservation is an axis-aligned rectangle with a half-open day interval.
* An item is placed once and does not move for the length of its stay.
* Two items whose stays overlap may not overlap in space.
* If item A sits in item B's exit channel (see geometry.corridor), then A's
  stay must be strictly nested inside B's stay, so B is never boxed in on a
  day it has to move in or out.

Two solvers
-----------
`solve` is the production path: a corner-point backtracking search, the
standard technique for rectangle packing, restricted to candidate coordinates
generated by already-placed neighbours.

`solve_exhaustive` is the oracle: the same backtracking search over *every*
integer coordinate in the space. It is exponential and only usable on small
instances, but it is complete, which is the entire point of having it.

For plain rectangle packing, corner-point placement is known to be complete:
any feasible packing can be slid down and left into a normalized one whose
items all touch either an edge or another item. The access constraint breaks
that argument, because sliding an item down is exactly the move that pushes it
into somebody else's exit channel. Whether that costs real solutions is an
empirical question, so `experiments.py` measures it against the oracle instead
of assuming either way.
"""

from dataclasses import dataclass

from .geometry import Rect, blocks, contains, orientations, overlaps
from .timeline import nested_within


@dataclass(frozen=True)
class Reservation:
    id: str
    w: int
    d: int
    start: int
    end: int
    rotatable: bool = False

    @property
    def area(self):
        return self.w * self.d


class SearchBudgetExceeded(Exception):
    pass


def _temporal_overlap(a, b):
    return a.start < b.end and b.start < a.end


def _pair_ok(res_a, rect_a, res_b, rect_b):
    """Check every constraint between one pair of placed items."""
    if not _temporal_overlap(res_a, res_b):
        return True
    if overlaps(rect_a, rect_b):
        return False
    if blocks(rect_b, rect_a) and not nested_within(res_b, res_a):
        return False
    if blocks(rect_a, rect_b) and not nested_within(res_a, res_b):
        return False
    return True


def check_placement(space_w, space_d, placed):
    """Validate a complete arrangement. `placed` is a list of (Reservation, Rect).

    Deliberately written as an independent O(n^2) recheck of the finished
    arrangement rather than reusing the incremental logic in the solver, so the
    tests can catch the solver accepting something it should not.
    """
    for res, rect in placed:
        if rect.w * rect.d != res.w * res.d:
            return False, "footprint area changed"
        if (rect.w, rect.d) != (res.w, res.d) and (rect.w, rect.d) != (res.d, res.w):
            return False, "footprint dimensions changed"
        if (rect.w, rect.d) != (res.w, res.d) and not res.rotatable:
            return False, "rotated a non-rotatable item: %s" % res.id
        if not contains(space_w, space_d, rect):
            return False, "out of bounds: %s" % res.id
    for i in range(len(placed)):
        for j in range(i + 1, len(placed)):
            res_a, rect_a = placed[i]
            res_b, rect_b = placed[j]
            if not _pair_ok(res_a, rect_a, res_b, rect_b):
                return False, "conflict between %s and %s" % (res_a.id, res_b.id)
    return True, "ok"


def _candidate_coords(reservations_placed, space_w, space_d, item_w, item_d):
    xs = {0}
    ys = {0}
    for _, rect in reservations_placed:
        xs.add(rect.x)
        xs.add(rect.x + rect.w)
        ys.add(rect.y)
        ys.add(rect.y + rect.d)
    xs = sorted(x for x in xs if 0 <= x <= space_w - item_w)
    ys = sorted(y for y in ys if 0 <= y <= space_d - item_d)
    return xs, ys


def _all_coords(space_w, space_d, item_w, item_d):
    return range(0, space_w - item_w + 1), range(0, space_d - item_d + 1)


def _search(space_w, space_d, items, fixed, exhaustive, budget):
    """Shared backtracking core. `fixed` is a list of (Reservation, Rect) that
    cannot move; `items` is the list of Reservations still to place."""
    placed = list(fixed)
    nodes = [0]

    def recurse(idx):
        if idx == len(items):
            return True
        res = items[idx]
        for (w, d) in orientations(res.w, res.d, res.rotatable):
            if w > space_w or d > space_d:
                continue
            if exhaustive:
                xs, ys = _all_coords(space_w, space_d, w, d)
            else:
                xs, ys = _candidate_coords(placed, space_w, space_d, w, d)
            for y in ys:
                for x in xs:
                    nodes[0] += 1
                    if nodes[0] > budget:
                        raise SearchBudgetExceeded()
                    rect = Rect(x, y, w, d)
                    ok = True
                    for other_res, other_rect in placed:
                        if not _pair_ok(res, rect, other_res, other_rect):
                            ok = False
                            break
                    if not ok:
                        continue
                    placed.append((res, rect))
                    if recurse(idx + 1):
                        return True
                    placed.pop()
        return False

    found = recurse(0)
    return found, placed if found else None, nodes[0]


def _order(reservations):
    """Largest first, ties broken deterministically.

    Big items have the fewest legal positions, so placing them while the space
    is still empty fails fast instead of deep in the tree. Standard practice in
    rectangle packing, and it is worth roughly an order of magnitude in nodes
    on these instances.
    """
    return sorted(reservations, key=lambda r: (-r.area, -max(r.w, r.d), r.id))


def solve(space_w, space_d, reservations, fixed=None, budget=400000):
    """Corner-point backtracking. Returns (feasible, placement, nodes).

    `placement` maps reservation id to Rect. `fixed` pins items that are
    already physically in the space and will not be moved.
    """
    fixed = fixed or []
    fixed_ids = {r.id for r, _ in fixed}
    todo = _order([r for r in reservations if r.id not in fixed_ids])
    try:
        found, placed, nodes = _search(space_w, space_d, todo, fixed, False, budget)
    except SearchBudgetExceeded:
        return None, None, budget
    if not found:
        return False, None, nodes
    return True, {res.id: rect for res, rect in placed}, nodes


def solve_exhaustive(space_w, space_d, reservations, fixed=None, budget=4000000):
    """Complete search over every integer position. Oracle only.

    Returns (feasible, placement, nodes), where feasible is None if the node
    budget ran out before the search finished, so callers can drop those
    instances instead of scoring them as a disagreement.
    """
    fixed = fixed or []
    fixed_ids = {r.id for r, _ in fixed}
    todo = _order([r for r in reservations if r.id not in fixed_ids])
    try:
        found, placed, nodes = _search(space_w, space_d, todo, fixed, True, budget)
    except SearchBudgetExceeded:
        return None, None, budget
    if not found:
        return False, None, nodes
    return True, {res.id: rect for res, rect in placed}, nodes
